### ISSUE TITLE
cannot make project

### ISSUE THREAD

**Issue by louisliu2048** [Safeheron/multi-party-ecdsa-cpp#1]
>  build git:(main) make
[ 79%] Built target MultiPartyEcdsa
[ 80%] Building CXX object test/CMakeFiles/gg18.key_gen_test.dir/gg18/key_gen_test.cpp.o
/Users/louisliu/golang/src/github.com/mpc/Safeheron/multi-party-ecdsa-cpp/test/gg18/key_gen_test.cpp:208:53: error: no member named 'STARK' in 'safeheron::curve::CurveType'
        testKeyGen_t_n(safeheron::curve::CurveType::STARK);
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
1 error generated.
make[2]: *** [test/CMakeFiles/gg18.key_gen_test.dir/gg18/key_gen_test.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/gg18.key_gen_test.dir/all] Error 2
make: *** [all] Error 2

**Comment by sword03** [comment]
The StarkCurve is not supported by OpenSSL. We have extended OpenSSL to support the StarkCurve. If you want to use the StarkCurve, you must install the [OpenSSL extended by Safeheron](https://github.com/Safeheron/openssl/tree/stark_curve) (refer to the "stark_curve" branch). Otherwise, you will get an error when you use the StarkCurve.

**Comment by Linode07** [comment]
> The StarkCurve is not supported by OpenSSL. We have extended OpenSSL to support the StarkCurve. If you want to use the StarkCurve, you must install the [OpenSSL extended by Safeheron](https://github.com/Safeheron/openssl/tree/stark_curve) (refer to the "stark_curve" branch). Otherwise, you will get an error when you use the StarkCurve.

I have used the version of openssl recommended, but I still get the error.

cmake .. -DOPENSSL_ROOT_DIR=/opt/openssl -DENABLE_TESTS=ON.

**Comment by sword03** [comment]
Use the branch “stark_curve" of repository “safeheron-crypto-suites-cpp”.

https://github.com/Safeheron/safeheron-crypto-suites-cpp/tree/stark_curve
